---
book_repo: docs-book
layout_repo: docs-layout

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

pcf_header: &local_pcf
  use_local_header: true
  latest_stable_version: 2.10
  changelog_href: https://docs.pivotal.io/application-service/2-10/overview/release-notes/runtime-rn.html
  local_header_img: /images/cloud_rings.png
  local_header_title: Tanzu Application Service for VMs
public_host: hello

sections:
  - repository:
      name: docs-content
    directory: azure-log-analytics-nozzle
    subnav_template: azure-log-analytics-nozzle_subnav.erb

template_variables:                             # optional
