---
book_repo: docs-book
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

pcf_header: &local_pcf
  use_local_header: true
  latest_stable_version: 2.10
  changelog_href: https://docs.pivotal.io/application-service/2-10/overview/release-notes/runtime-rn.html
  local_header_img: /images/cloud_rings.png
  local_header_title: Tanzu Application Service for VMs

sections:
  - repository:
      name: docs-content
    directory: azure-log-analytics-nozzle
    subnav_template: azure-log-analytics-nozzle_subnav.erb

template_variables:
  book_title: VMware Tanzu Documentation
  book_title_short: VMware Tanzu Docs
  url_path: https://docs.pivotal.io/azure-log-analytics-nozzle
  title: <span class="title-deemph">VMware Tanzu</span> Documentation
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation to help you install, understand, and succeed with VMware Tanzu enterprise-grade software."
  product_url: https://network.pivotal.io/products/pivotal-cf
  support_link: <a href="https://pivotal.io/support" target="_blank">Support</a>
  support_call_to_action: <a href="https://pivotal.io/support" target="_blank">Need Support?</a>
  support_url: https://pivotal.io/support
  use_global_header: true
  global_header_product_href: https://network.pivotal.io/
  global_header_product_link_text: Downloads
